[theme]
primaryColor="#001E62"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#f7c2c2"
textColor="#512647"
font="sans serif"

[server]
port = 9500
runOnSave = false

[browser]
gatherUsageStats = false